### ISSUE TITLE
Was homework communicated?

### ISSUE THREAD

**Issue by liamhuber** [pyiron/pyiron_developer_tutorial#5]
Has the homework been communicated to attendees?
- go on google and know the following terms in the context of python: "function", "argument", "class", "method", "property", "module". Bonus term: "decorator"
- [install conda](https://docs.anaconda.com/anaconda/install/)
- [install pycharm](https://www.jetbrains.com/help/pycharm/installation-guide.html#toolbox)
- [make a new conda virtual env](https://www.jetbrains.com/help/pycharm/conda-support-creating-conda-virtual-environment.html#d7ee133d)
- [add pyiron to it](https://www.jetbrains.com/help/pycharm/installing-uninstalling-and-upgrading-packages.html#interpreter-settings) ([be sure to set your only source to `https://conda.anaconda.org/conda-forge/`](https://www.jetbrains.com/help/pycharm/installing-uninstalling-and-upgrading-packages.html#custom-repositories)

I don't want to burn through the first 0.5-1hr just getting the bare bones installed on everyone's machine.

@samwaseda, I think you're the face of this operation, have you/would you send around an e-mail to the attendees with some instruction?

EDIT: Updated homework with instruction links

**Comment by samwaseda** [comment]
Sure, I'll do it :) Thanks for the links!
